services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: mediamtx
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    environment:
      MTX_RTSPTRANSPORTS: tcp
      MTX_WEBRTCADDITIONALHOSTS: ${MTX_WEBRTCADDITIONALHOSTS:-127.0.0.1}
    ports:
      - "8555:8555"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"